server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=identity_service;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456A@$
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect